package com.h2db.model;
// Generated Feb 24, 2017 9:36:16 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * CurrentDeptEmp generated by hbm2java
 */
@Entity
@Table(name = "CURRENT_DEPT_EMP")
public class CurrentDeptEmp implements java.io.Serializable {

	private CurrentDeptEmpId id;

	public CurrentDeptEmp() {
	}

	public CurrentDeptEmp(CurrentDeptEmpId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "deptNo", column = @Column(name = "DEPT_NO", nullable = false, length = 4) ),
			@AttributeOverride(name = "empNo", column = @Column(name = "EMP_NO", nullable = false) ),
			@AttributeOverride(name = "fromDate", column = @Column(name = "FROM_DATE", nullable = false, length = 23) ),
			@AttributeOverride(name = "toDate", column = @Column(name = "TO_DATE", nullable = false, length = 23) ) })
	public CurrentDeptEmpId getId() {
		return this.id;
	}

	public void setId(CurrentDeptEmpId id) {
		this.id = id;
	}

}
