package com.h2db.model;
// Generated Feb 24, 2017 9:36:16 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DeptManagerId generated by hbm2java
 */
@Embeddable
public class DeptManagerId implements java.io.Serializable {

	private String deptNo;
	private int empNo;

	public DeptManagerId() {
	}

	public DeptManagerId(String deptNo, int empNo) {
		this.deptNo = deptNo;
		this.empNo = empNo;
	}

	@Column(name = "DEPT_NO", nullable = false, length = 4)
	public String getDeptNo() {
		return this.deptNo;
	}

	public void setDeptNo(String deptNo) {
		this.deptNo = deptNo;
	}

	@Column(name = "EMP_NO", nullable = false)
	public int getEmpNo() {
		return this.empNo;
	}

	public void setEmpNo(int empNo) {
		this.empNo = empNo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DeptManagerId))
			return false;
		DeptManagerId castOther = (DeptManagerId) other;

		return ((this.getDeptNo() == castOther.getDeptNo()) || (this.getDeptNo() != null
				&& castOther.getDeptNo() != null && this.getDeptNo().equals(castOther.getDeptNo())))
				&& (this.getEmpNo() == castOther.getEmpNo());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getDeptNo() == null ? 0 : this.getDeptNo().hashCode());
		result = 37 * result + this.getEmpNo();
		return result;
	}

}
