package com.h2db.model;
// Generated Feb 24, 2017 9:36:16 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * DeptEmpLatestDate generated by hbm2java
 */
@Entity
@Table(name = "DEPT_EMP_LATEST_DATE")
public class DeptEmpLatestDate implements java.io.Serializable {

	private DeptEmpLatestDateId id;

	public DeptEmpLatestDate() {
	}

	public DeptEmpLatestDate(DeptEmpLatestDateId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "empNo", column = @Column(name = "EMP_NO", nullable = false) ),
			@AttributeOverride(name = "fromDate", column = @Column(name = "FROM_DATE", nullable = false, length = 23) ),
			@AttributeOverride(name = "toDate", column = @Column(name = "TO_DATE", nullable = false, length = 23) ) })
	public DeptEmpLatestDateId getId() {
		return this.id;
	}

	public void setId(DeptEmpLatestDateId id) {
		this.id = id;
	}

}
