package com.h2db.model;
// Generated Feb 24, 2017 9:36:16 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Employees generated by hbm2java
 */
@Entity
@Table(name = "EMPLOYEES")
public class Employees implements java.io.Serializable {

	private int empNo;
	private Date birthDate;
	private String firstName;
	private String gender;
	private Date hireDate;
	private String lastName;
	private Set<DeptManager> deptManagers = new HashSet<DeptManager>(0);
	private Set<Salaries> salarieses = new HashSet<Salaries>(0);
	private Set<DeptEmp> deptEmps = new HashSet<DeptEmp>(0);
	private Set<Titles> titleses = new HashSet<Titles>(0);

	public Employees() {
	}

	public Employees(int empNo, Date birthDate, String firstName, String gender, Date hireDate, String lastName) {
		this.empNo = empNo;
		this.birthDate = birthDate;
		this.firstName = firstName;
		this.gender = gender;
		this.hireDate = hireDate;
		this.lastName = lastName;
	}

	public Employees(int empNo, Date birthDate, String firstName, String gender, Date hireDate, String lastName,
			Set<DeptManager> deptManagers, Set<Salaries> salarieses, Set<DeptEmp> deptEmps, Set<Titles> titleses) {
		this.empNo = empNo;
		this.birthDate = birthDate;
		this.firstName = firstName;
		this.gender = gender;
		this.hireDate = hireDate;
		this.lastName = lastName;
		this.deptManagers = deptManagers;
		this.salarieses = salarieses;
		this.deptEmps = deptEmps;
		this.titleses = titleses;
	}

	@Id

	@Column(name = "EMP_NO", unique = true, nullable = false)
	public int getEmpNo() {
		return this.empNo;
	}

	public void setEmpNo(int empNo) {
		this.empNo = empNo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "BIRTH_DATE", nullable = false, length = 8)
	public Date getBirthDate() {
		return this.birthDate;
	}

	public void setBirthDate(Date birthDate) {
		this.birthDate = birthDate;
	}

	@Column(name = "FIRST_NAME", nullable = false, length = 14)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "GENDER", nullable = false, length = 1)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "HIRE_DATE", nullable = false, length = 8)
	public Date getHireDate() {
		return this.hireDate;
	}

	public void setHireDate(Date hireDate) {
		this.hireDate = hireDate;
	}

	@Column(name = "LAST_NAME", nullable = false, length = 16)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employees")
	public Set<DeptManager> getDeptManagers() {
		return this.deptManagers;
	}

	public void setDeptManagers(Set<DeptManager> deptManagers) {
		this.deptManagers = deptManagers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employees")
	public Set<Salaries> getSalarieses() {
		return this.salarieses;
	}

	public void setSalarieses(Set<Salaries> salarieses) {
		this.salarieses = salarieses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employees")
	public Set<DeptEmp> getDeptEmps() {
		return this.deptEmps;
	}

	public void setDeptEmps(Set<DeptEmp> deptEmps) {
		this.deptEmps = deptEmps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employees")
	public Set<Titles> getTitleses() {
		return this.titleses;
	}

	public void setTitleses(Set<Titles> titleses) {
		this.titleses = titleses;
	}

}
